export const PERMISSIONS = {
  ADMIN_ACCESS: 'admin.access',
  USERS_READ: 'users.read',
  USERS_MANAGE: 'users.manage',
  ROLES_READ: 'roles.read',
  ROLES_MANAGE: 'roles.manage',
  PORTFOLIO_READ: 'portfolio.read',
  PORTFOLIO_MANAGE: 'portfolio.manage',
  CONTENT_READ: 'content.read',
  CONTENT_MANAGE: 'content.manage',
  MEDIA_READ: 'media.read',
  MEDIA_CREATE: 'media.create',
  MEDIA_UPDATE: 'media.update',
  MEDIA_DELETE: 'media.delete',
  MEDIA_MANAGE: 'media.manage',
  ANALYTICS_READ: 'analytics.read',
  SETTINGS_READ: 'settings.read',
  SETTINGS_UPDATE: 'settings.update',
  CHAT_USE: 'chat.use',
  CHAT_TEAM_READ: 'chat.team.read',
  CHAT_TEAM_WRITE: 'chat.team.write',
  CHAT_DM_CREATE: 'chat.dm.create',
  CHAT_AI_USE: 'chat.ai.use',
  CHAT_MODERATE: 'chat.moderate',
  FRIENDS_READ: 'friends.read',
  FRIENDS_INVITE: 'friends.invite',
  FRIENDS_MANAGE: 'friends.manage',
  TEAMS_READ: 'teams.read',
  TEAMS_CREATE: 'teams.create',
  TEAMS_MANAGE: 'teams.manage',
  TEAMS_MEMBERS_MANAGE: 'teams.members.manage',
  NOTIFICATIONS_READ: 'notifications.read',
  NOTIFICATIONS_MANAGE: 'notifications.manage',
  CALENDAR_READ: 'calendar.read',
  CALENDAR_WRITE: 'calendar.write',
  CALENDAR_TEAM_READ: 'calendar.team.read',
  CALENDAR_TEAM_WRITE: 'calendar.team.write',
  CALENDAR_INVITE: 'calendar.invite',
  CALENDAR_ADMIN: 'calendar.admin'
} as const

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]

export const PERMISSION_META: Record<PermissionKey, { label: string, group: string }> = {
  'admin.access': { label: 'Dostęp do panelu admina', group: 'Admin' },
  'users.read': { label: 'Podgląd użytkowników', group: 'Users' },
  'users.manage': { label: 'Zarządzanie użytkownikami', group: 'Users' },
  'roles.read': { label: 'Podgląd ról', group: 'Roles' },
  'roles.manage': { label: 'Zarządzanie rolami', group: 'Roles' },
  'portfolio.read': { label: 'Podgląd portfolio', group: 'Portfolio' },
  'portfolio.manage': { label: 'Zarządzanie portfolio', group: 'Portfolio' },
  'content.read': { label: 'Podgląd treści', group: 'Content' },
  'content.manage': { label: 'Zarządzanie treściami', group: 'Content' },
  'media.read': { label: 'Podgląd własnych mediów', group: 'Media' },
  'media.create': { label: 'Upload mediów', group: 'Media' },
  'media.update': { label: 'Edycja metadanych mediów', group: 'Media' },
  'media.delete': { label: 'Usuwanie mediów', group: 'Media' },
  'media.manage': { label: 'Zarządzanie wszystkimi mediami', group: 'Media' },
  'analytics.read': { label: 'Podgląd analityki', group: 'Analytics' },
  'settings.read': { label: 'Podgląd ustawień', group: 'Settings' },
  'settings.update': { label: 'Edycja ustawień', group: 'Settings' },
  'chat.use': { label: 'Korzystanie z czatu', group: 'Chat' },
  'chat.team.read': { label: 'Podglad czatu zespolow', group: 'Chat' },
  'chat.team.write': { label: 'Pisanie w czatach zespolow', group: 'Chat' },
  'chat.dm.create': { label: 'Tworzenie DM', group: 'Chat' },
  'chat.ai.use': { label: 'Korzystanie z AI chat', group: 'Chat' },
  'chat.moderate': { label: 'Moderacja czatu', group: 'Chat' },
  'friends.read': { label: 'Podgląd znajomych', group: 'Friends' },
  'friends.invite': { label: 'Wysyłanie zaproszeń do znajomych', group: 'Friends' },
  'friends.manage': { label: 'Zarządzanie znajomymi', group: 'Friends' },
  'teams.read': { label: 'Podgląd zespołów', group: 'Teams' },
  'teams.create': { label: 'Tworzenie zespołów', group: 'Teams' },
  'teams.manage': { label: 'Zarządzanie zespołami', group: 'Teams' },
  'teams.members.manage': { label: 'Zarządzanie członkami zespołu', group: 'Teams' },
  'notifications.read': { label: 'Odczyt powiadomień', group: 'Notifications' },
  'notifications.manage': { label: 'Zarządzanie powiadomieniami', group: 'Notifications' },
  'calendar.read': { label: 'Podgląd kalendarza', group: 'Calendar' },
  'calendar.write': { label: 'Tworzenie i edycja wydarzeń', group: 'Calendar' },
  'calendar.team.read': { label: 'Podgląd kalendarza zespołu', group: 'Calendar' },
  'calendar.team.write': { label: 'Edycja wydarzeń zespołowych', group: 'Calendar' },
  'calendar.invite': { label: 'Zapraszanie do wydarzeń', group: 'Calendar' },
  'calendar.admin': { label: 'Administracja kalendarzem', group: 'Calendar' }
}
